### ISSUE TITLE
Remove the Add row option on form

### ISSUE THREAD

**Issue by DanielScott4** [VHAINNOVATIONS/LEAF#1407]
Does anyone know how to remove the Add Row button on a form Grid (Table Input)?

**Comment by pete-nerantzinis** [comment]
> Does anyone know how to remove the Add Row button on a form Grid (Table Input)?

This can be done through Advanced Options on the form indicator that holds the grid input.

**Comment by DanielScott4** [comment]
I have tried that and it does not seem to work.
![image](https://user-images.githubusercontent.com/68380553/124953417-236f5080-dfe3-11eb-8cfd-957ed84729e9.png)

**Comment by DanielScott4** [comment]
Never mind I figured it out it does not work if you put it in the advanced options on the grid input. You have to do it somewhere else on the form.
