### ISSUE TITLE
localtesting branch readme.md

### ISSUE THREAD

**Issue by jonesdlwa** [VHAINNOVATIONS/LEAF#3]
Master branch references the localtesting branch for guidance on setup on a non-VA server; however, the readme.md is the same for both branches. Can this be updated to have more information on setting up LEAF for non-VA/outside of VA things?

Thanks!

**Comment by nathanws** [comment]
We're currently working on better setup documentation. Though it may be awhile before LEAF is usable outside of the VA environment.
